### PR TITLE
WIP: Updating the driver

### PR DESCRIPTION
**Pull request by mamercad**
This isn't ready or anything ...

### CODE REVIEW

**Comment by mamercad** [comment]
It's using the presumably deprecated `molecule_header` filter.

**Comment by mamercad** [comment]
Getting closer: https://gist.github.com/mamercad/92aee19708c2abde9e1b6467f957a540

**Comment by mamercad** [comment]
This is working end-to-end now: https://gist.github.com/mamercad/3bb5538b8f35d270b247e2f5ac30083f

**Comment by mamercad** [comment]
Sanity check is working pretty well:

```
INFO     Sanity checks: 'digitalocean'
CRITICAL Please ensure that one of the following environment variables are set: DO_API_TOKEN,DO_API_KEY,DO_OAUTH_TOKEN,OAUTH_TOKEN
```

**Comment by mamercad** [comment]
```
❯ env | grep DO_API_TO
DO_API_TOKEN=asdf
```

Yields:

```
INFO     Sanity checks: 'digitalocean'
CRITICAL Failed to authentication to DigitalOcean, please ensure the validity of your DO API token. The environment variable DO_API_TOKEN is currently defined.
```

**Comment by mamercad** [comment]
@ssbarnea @tadeboro How's this looking so far?

**Comment by ssbarnea** [comment]
@mamercad too many changes in one PR to make it possible to review. Still, that does not make it bad. I would recommend a run of black first.

**Comment by mamercad** [comment]
> @mamercad too many changes in one PR to make it possible to review. Still, that does not make it bad. I would recommend a run of black first.

```
❯ black src 
All done! ✨ 🍰 ✨
16 files left unchanged.
```

**Comment by tadeboro** [comment]
@mamercad Thank you a ton for working on this. You seriously rock!

I am currently busy with other things at $job, but I will try to have a closer look at the end of the week.

As for the PR size, I do not mind it that much since things were in terrible shape, and single-PR revamps get things fixed way faster than incremental fixes that need to work around things like bad CI setups, etc.

Thank you again for taking care of this!

**Comment by mamercad** [comment]
@ssbarnea Lint is passing, tox is running, just a quick update.

**Comment by mamercad** [comment]
> @ssbarnea Lint is passing, tox is running, just a quick update.

What was the idea for `patched_config_validate`?

**Pull request closed without merging**
